### ISSUE TITLE
FileNotFound Error

### ISSUE THREAD

**Issue by ev1l0rd** [bindh3x/pas#1]
Error log:

```
ev1l0rd@ev1l0rd:~/temp/pas$ pas a test
Traceback (most recent call last):
  File "/usr/local/bin/pas", line 11, in <module>
    load_entry_point('pas==1.0', 'console_scripts', 'pas')()
  File "/usr/local/lib/python3.5/dist-packages/pas/__init__.py", line 186, in main
    pas = Pas()
  File "/usr/local/lib/python3.5/dist-packages/pas/__init__.py", line 56, in __init__
    self.items = self.load()
  File "/usr/local/lib/python3.5/dist-packages/pas/__init__.py", line 95, in load
    with open(self.temp_file, "rt") as temp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpdlqpm88f.pass'

```

Installed using instructions from README.md + Including config variables set.

Running Ubuntu 16.04.

**Comment by bindh3x** [comment]
Hi @ev1l0rd  @megaduks.

This can be caused by:
1. There is no private key.
2. GPG path not found and `pas` cannot create the new safe.

The safe exists?
```{bash}
$ file /home/user/.gnupg/safe.gpg
```

and:
> put this environment variables in your .bashrc/.zshrc file:
export PAS_GPG_HOME="/home/$USER/.gnupg"
export PAS_GPG_RECIPIENT="Your name"

**Comment by ev1l0rd** [comment]
@bindh3x - No, my version of GPG does not have a safe.gpg file. I do have several private keys (one of them I use to verify my commits on this very site). Here is a list of all gpg files in my $USER/.gnupg directory (excluding subfolders):

```
ev1l0rd@ev1l0rd:~/.gnupg$ ll *.gpg
-rwx------ 1 ev1l0rd ev1l0rd 67071 mei  3 17:59 pubring.gpg*
-rwx------ 1 ev1l0rd ev1l0rd 15064 mrt 22 18:02 secring.gpg*
-rwx------ 1 ev1l0rd ev1l0rd  1720 mei  3 17:59 trustdb.gpg*
```

Maybe one of these files will be of use to you instead for your script.

I have put in the following in my `~/.bashrc` file (which is the one that is loaded):
```
export PAS_GPG_HOME="/home/$USER/.gnupg"
export PAS_GPG_RECIPIENT="Valentijn Vermeij"
```

**Comment by bindh3x** [comment]
@ev1l0rd that's should fix it:

```{bash}
$ echo "{}" > safe.txt
$ gpg --output safe.gpg --encrypt -r "Private key email" safe.txt
$ mv safe.gpg /home/USER/.gnupg/
$ pas add test
```

If your private key is using specific email address then set:
```{bash}
export PAS_GPG_RECIPIENT="you@example.com"
```

**Comment by ev1l0rd** [comment]
@bindh3x - After doing as you said, I still get the error. I have also checked /tmp, and temp files for pas do exist there.

Output of `ll ~/..gpg`:

```
ev1l0rd@ev1l0rd:~/.gnupg$ ll *.gpg
-rwx------ 1 ev1l0rd ev1l0rd 68271 jun 28 16:02 pubring.gpg*
-rw-rw-r-- 1 ev1l0rd ev1l0rd   343 jun 28 16:03 safe.gpg
-rwx------ 1 ev1l0rd ev1l0rd 15064 mrt 22 18:02 secring.gpg*
-rwx------ 1 ev1l0rd ev1l0rd  1800 jun 28 16:02 trustdb.gpg*
```
